import { PinoutCard, PinoutCardsArray } from "./PinoutCard.js";

//var pinout = new PinoutCard("Title", "Description", "Image File Path", "type", "manufacturer");
var arduinoUnoR3 = new PinoutCard("Arduino Uno R3", "Arduino Uno is a microcontroller board based on the ATmega328P. It has 14 digital input/output pins (of which 6 can be used as PWM outputs), 6 analog inputs, a 16 MHz ceramic resonator (CSTCE16M0V53-R0), a USB connection, a power jack, an ICSP header and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started.. You can tinker with your Uno without worrying too much about doing something wrong, worst case scenario you can replace the chip for a few dollars and start over again.", "pinouts/Arduino Uno R3 Pinout.png", "microcontroller", "Arduino LLC");
var arduinoLeonardo = new PinoutCard("Arduino Leonardo", "Arduino Leonardo is a microcontroller board based on the ATmega32u4. It has 20 digital input/output pins (of which 7 can be used as PWM outputs and 12 as analog inputs), a 16 MHz crystal oscillator, a micro USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Leonardo differs from all preceding boards in that the ATmega32u4 has built-in USB communication, eliminating the need for a secondary processor. This allows the Leonardo to appear to a connected computer as a mouse and keyboard, in addition to a virtual (CDC) serial / COM port. It also has other implications for the behavior of the board; these are detailed on the Getting started with the Arduino Leonardo.", "pinouts/Arduino Leonardo Pinout.png", "microcontroller", "Arduino LLC");
var arduinoMegaR3 = new PinoutCard("Arduino Mega 2560 R3", "The Arduino Mega 2560 is a microcontroller board based on the ATmega2560. It has 54 digital input/output pins (of which 15 can be used as PWM outputs), 16 analog inputs, 4 UARTs (hardware serial ports), a 16 MHz crystal oscillator, a USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Mega 2560 board is compatible with most shields designed for the Uno and the former boards Duemilanove or Diecimila. The Mega 2560 is an update to the Arduino Mega, which it replaces.", "pinouts/Arduino Mega R3 Pinout.png", "microcontroller", "Arduino LLC");
var arduinoNanoESP32 = new PinoutCard("Arduino Nano ESP32", "Introducing the Nano ESP32, a powerful addition to the Arduino ecosystem that brings the popular ESP32-S3 to the world of Arduino and MicroPython programming. Whether you're a beginner stepping into the world of IoT or MicroPython, or an advanced user looking to incorporate it into your next product, the Nano ESP32 is the perfect choice. It covers all your needs to kick-start your IoT or MicroPython project with ease.", "pinouts/Arduino Nano ESP32 Pinout.png", "microcontroller", "Arduino LLC");
var arduinoUnoR4Minima = new PinoutCard("Arduino Uno R4 Minima", "Enhanced and improved, the Arduino UNO R4 Minima is armed with a powerful 32-bit microcontroller courtesy of Renesas. Brace yourself for increased processing power, expanded memory, and a whole new level of on-board peripherals. The best part? Compatibility with existing shields and accessories remains intact, and there's no need to make any changes to the standard form factor or 5 V operating voltage. Joining the Arduino ecosystem, the UNO R4 is a trusty addition suitable for both beginners and seasoned electronics enthusiasts. Whether you're just starting out or looking to push the boundaries of your projects, this robust board delivers reliable performance every time.", "pinouts/Arduino Uno R4 Minima Pinout.png", "microcontroller", "Arduino LLC");
var raspberryPiPico = new PinoutCard("Raspberry Pi Pico", "The Raspberry Pi Pico series is a range of tiny, fast, and versatile boards built using RP2040, the flagship microcontroller chip designed by Raspberry Pi in the UK", "pinouts/Raspberry Pi Pico Pinout.svg", "microcontroller", "Raspberry Pi Corporation");
var raspberryPiPicoW = new PinoutCard("Raspberry Pi Pico W", "The Raspberry Pi Pico series is a range of tiny, fast, and versatile boards built using RP2040, the flagship microcontroller chip designed by Raspberry Pi in the UK", "pinouts/Raspberry Pi Pico W Pinout.svg", "microcontroller", "Raspberry Pi Corporation");
