import { PinoutCard, PinoutCardsArray } from "./PinoutCard.js";

//var pinout = new PinoutCard("Title", "Description", "Image File Path", "type", "manufacturer");
var arduinoUnoR3 = new PinoutCard("Arduino Uno R3", "Arduino Uno is a microcontroller board based on the ATmega328P. It has 14 digital input/output pins (of which 6 can be used as PWM outputs), 6 analog inputs, a 16 MHz ceramic resonator (CSTCE16M0V53-R0), a USB connection, a power jack, an ICSP header and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started.. You can tinker with your Uno without worrying too much about doing something wrong, worst case scenario you can replace the chip for a few dollars and start over again.", "pinouts/Arduino Uno R3 Pinout.png", "microcontroller", "Arduino LLC");
var arduinoLeonardo = new PinoutCard("Arduino Leonardo", "Arduino Leonardo is a microcontroller board based on the ATmega32u4. It has 20 digital input/output pins (of which 7 can be used as PWM outputs and 12 as analog inputs), a 16 MHz crystal oscillator, a micro USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Leonardo differs from all preceding boards in that the ATmega32u4 has built-in USB communication, eliminating the need for a secondary processor. This allows the Leonardo to appear to a connected computer as a mouse and keyboard, in addition to a virtual (CDC) serial / COM port. It also has other implications for the behavior of the board; these are detailed on the Getting started with the Arduino Leonardo.", "pinouts/Arduino Leonardo Pinout.png", "microcontroller", "Arduino LLC");
var arduinoMegaR3 = new PinoutCard("Arduino Mega 2560 R3", "The Arduino Mega 2560 is a microcontroller board based on the ATmega2560. It has 54 digital input/output pins (of which 15 can be used as PWM outputs), 16 analog inputs, 4 UARTs (hardware serial ports), a 16 MHz crystal oscillator, a USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Mega 2560 board is compatible with most shields designed for the Uno and the former boards Duemilanove or Diecimila. The Mega 2560 is an update to the Arduino Mega, which it replaces.", "pinouts/Arduino Mega R3 Pinout.png", "microcontroller", "Arduino LLC");
var arduinoNanoESP32 = new PinoutCard("Arduino Nano ESP32", "Introducing the Nano ESP32, a powerful addition to the Arduino ecosystem that brings the popular ESP32-S3 to the world of Arduino and MicroPython programming. Whether you're a beginner stepping into the world of IoT or MicroPython, or an advanced user looking to incorporate it into your next product, the Nano ESP32 is the perfect choice. It covers all your needs to kick-start your IoT or MicroPython project with ease.", "pinouts/Arduino Nano ESP32 Pinout.png", "microcontroller", "Arduino LLC");
var arduinoUnoR4Minima = new PinoutCard("Arduino Uno R4 Minima", "Enhanced and improved, the Arduino UNO R4 Minima is armed with a powerful 32-bit microcontroller courtesy of Renesas. Brace yourself for increased processing power, expanded memory, and a whole new level of on-board peripherals. The best part? Compatibility with existing shields and accessories remains intact, and there's no need to make any changes to the standard form factor or 5 V operating voltage. Joining the Arduino ecosystem, the UNO R4 is a trusty addition suitable for both beginners and seasoned electronics enthusiasts. Whether you're just starting out or looking to push the boundaries of your projects, this robust board delivers reliable performance every time.", "pinouts/Arduino Uno R4 Minima Pinout.png", "microcontroller", "Arduino LLC");
var raspberryPiPico = new PinoutCard("Raspberry Pi Pico", "The Raspberry Pi Pico series is a range of tiny, fast, and versatile boards built using RP2040, the flagship microcontroller chip designed by Raspberry Pi in the UK", "pinouts/Raspberry Pi Pico Pinout.svg", "microcontroller", "Raspberry Pi Corporation");
var raspberryPiPicoW = new PinoutCard("Raspberry Pi Pico W", "The Raspberry Pi Pico series is a range of tiny, fast, and versatile boards built using RP2040, the flagship microcontroller chip designed by Raspberry Pi in the UK", "pinouts/Raspberry Pi Pico W Pinout.svg", "microcontroller", "Raspberry Pi Corporation");
var raspberryPiPico2 = new PinoutCard("Raspberry Pi Pico 2", "With a higher core clock speed, double the memory, more powerful Arm cores, optional RISC‑V cores, new security features, and upgraded interfacing capabilities, Raspberry Pi Pico 2 delivers a significant performance boost, while retaining compatibility with earlier members of the Raspberry Pi Pico series. Programmable in C / C++ and Python, and with detailed documentation, Raspberry Pi Pico 2 is the ideal microcontroller board for enthusiasts and professional developers alike.", "pinouts/Raspberry Pi Pico 2 Pinout.svg", "microcontroller", "Raspberry Pi Corporation");
var raspberryPiPico2W = new PinoutCard("Raspberry Pi Pico 2 W", "With a higher core clock speed, double the memory, more powerful Arm cores, optional RISC‑V cores, new security features, and upgraded interfacing capabilities, Raspberry Pi Pico 2 delivers a significant performance boost, while retaining compatibility with earlier members of the Raspberry Pi Pico series. Programmable in C / C++ and Python, and with detailed documentation, Raspberry Pi Pico 2 is the ideal microcontroller board for enthusiasts and professional developers alike.", "pinouts/Raspberry Pi Pico 2W Pinout.svg", "microcontroller", "Raspberry Pi Corporation");
// var raspberryPi5B = new PinoutCard();
// var raspberryPi4B = new PinoutCard();
// var raspberryPi3B = new PinoutCard();
// var raspberryPi3BPlus = new PinoutCard();
// var raspberryPi3A = new PinoutCard();
// var raspberryPi3APlus = new PinoutCard();
// var raspberryPiZero = new PinoutCard();
// var raspberryPiZeroW = new PinoutCard();
// var raspberryPiZero2W = new PinoutCard();
var arduinoGigaR1 = new PinoutCard("Arduino Giga R1 WiFi", "The Arduino GIGA R1 WiFi is designed for ambitious makers who want to step up their game. It levels the playing field for gamers, artists, sound designers and anyone coming to the tech world with big ideas on a budget – because it packs advanced features into an accessible component, with the same form factor as our popular Mega and Due. Let’s break down all the powerful features of this board. Microcontroller (STM32H747XI): This dual core 32-bits microcontroller allows you have two brain talking to each other (a Cortex®-M7 at 480 MHz and a Cortex®-M4 at 240 MHz) you can even run micropython in one and Arduino in the other. Wireless communication (Murata 1DX):  Whether you prefer Wi-Fi® or Bluetooth®, the GIGA R1 WiFi got you covered. You can even quickly connect to the Arduino IoT Cloud and keep track of your project remotely. And if you are concerned about the security of the communication, the ATECC608A keeps everything under control. Hardware ports and communication: Following the legacy of the Arduino Mega and the Arduino Due, the GIGA R1 WiFi has 4 UARTs (hardware serial ports), 3 I2C ports (1 more than its predecessors), 2 SPI ports (1 more than its predecessors), 1 FDCAN. GPIOs and extra pins: We wanted to keep the same form factor of the Mega and the Due, so you can easily adapt your custom made shields to the GIGA R1 WiFi (remember this board works at 3.3V though!) and we added extra headers to access extra pins, leaving the total count to 76 GPIO pins, and the best part, you can access them from underneath, so keep your project as it is and just think on how to expand it. Also, we added two new pins: a VRTC so you can connect a battery to keep the RTC running while the board is off and an OFF pin so you can shut down the board. Connectors: The GIGA R1 WiFi has extra connectors on board which will facilitate the creation of your project without any extra hardware. This board has: USB-A connector suitable for hosting USB sticks, other mass storage devices and HID devices such as keyboard or mouse. 3.5mm input-output jack connected to DAC0, DAC1 and A7. USB-C® to power and program the board, as well as simulate an HID device such as mouse or keyboard. Jtag connector, 2x5 1.27mm. 20 pin Arducam camera connector. Higher voltage support: In comparison with its predecessors that support up to 12 volts, the GIGA R1 WiFi can handle a range of 6 to 24 volts.", "pinouts/Arduino Giga R1 Wifi Pinout.png", "microcontroller", "Arduino LLC");
var arduinoNano = new PinoutCard("Arduino Nano", "Introducing the Nano ESP32, a powerful addition to the Arduino ecosystem that brings the popular ESP32-S3 to the world of Arduino and MicroPython programming. Whether you're a beginner stepping into the world of IoT or MicroPython, or an advanced user looking to incorporate it into your next product, the Nano ESP32 is the perfect choice. It covers all your needs to kick-start your IoT or MicroPython project with ease.", "pinouts/Arduino Nano Pinout.png", "microcontroller", "Arduino LLC");
var arduinoUnoR4Wifi = new PinoutCard("Arduino Uno R4 WiFi", "The Arduino UNO R4 WiFi combines the processing power and exciting new peripherals of the RA4M1 microcontroller from Renesas with the wireless connectivity power of the ESP32-S3 from Espressif. On top of this, the UNO R4 WiFi offers an on-board 12x8 LED matrix, Qwiic connector, VRTC, and OFF pin, covering all potential needs makers will have for their next project. With the UNO R4 WiFi, you can easily upgrade your project and add wireless connectivity to expand the reach of your current setup. If this is your first project, this board has everything you need to spark your creativity.", "pinouts/Arduino Uno R4 Wifi Pinout.png");
var transistor2n2222 = new PinoutCard("2n2222 Transistor", "Achieve superior performance in your electronic projects with the 2N2222 Silicon NPN Transistor from Solid State Manufacturing. Designed for buyers, maintainers, and professionals, this transistor ensures reliability and efficiency in various applications.", "pinouts/2N2222 Pinout.png", "transistor", "Solid State Manufacturing");
//var arduino